### ISSUE TITLE
我用倍加福雷达按照参数设置成1800个点，实际结果非常不准，里程计起飞。

### ISSUE THREAD

**Issue by ZOUJIASHUAI** [bzdfzfer/circle_odometry#3]
@bzdfzfer

**Comment by bzdfzfer** [comment]
抱歉才刚刚看到，我做实验用的就是倍加福雷达，麻烦您提供一下数据。

**Comment by bzdfzfer** [comment]
> 抱歉才刚刚看到，我做实验用的就是倍加福雷达，麻烦您提供一下数据。

倍加福激光数据有个小坑，他的激光点的排布不是连续的，是对立排列，简单举例说明一下这个现象，一个0度点接一个180度点，然后是1度点181度点。如果您处理该数据时，请把点调整到按照扫描角度连续排列的形式，这样才能提取出有效的线段信息。
